const sqlite3 = require("sqlite3").verbose();
const path = require("path");

const dbPath = path.join(__dirname, "english_lab.db");
const db = new sqlite3.Database(dbPath);

console.log("Creating and populating english_lab.db...");

db.serialize(() => {
  // 1. Chapters Table
  db.run(`
    CREATE TABLE IF NOT EXISTS chapters (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      chapter_number INTEGER NOT NULL,
      title TEXT NOT NULL,
      description TEXT,
      cefr_level TEXT NOT NULL
    );
  `);

  // 2. Grammar Topics Table
  db.run(`
    CREATE TABLE IF NOT EXISTS grammar_topics (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      chapter_id INTEGER,
      topic_code TEXT NOT NULL,
      title TEXT NOT NULL,
      explanation TEXT NOT NULL,
      example_sentence TEXT,
      cefr_level TEXT NOT NULL,
      FOREIGN KEY (chapter_id) REFERENCES chapters(id)
    );
  `);

  // 3. Quiz Questions Table
  db.run(`
    CREATE TABLE IF NOT EXISTS quiz_questions (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      topic_id INTEGER,
      question_text TEXT NOT NULL,
      option_a TEXT NOT NULL,
      option_b TEXT NOT NULL,
      option_c TEXT,
      option_d TEXT,
      correct_option TEXT NOT NULL,
      explanation TEXT,
      cefr_level TEXT NOT NULL,
      FOREIGN KEY (topic_id) REFERENCES grammar_topics(id)
    );
  `);

  // 4. Vocabulary Flashcards Table
  db.run(`
    CREATE TABLE IF NOT EXISTS vocabulary (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      english_word TEXT NOT NULL,
      swedish_translation TEXT NOT NULL,
      part_of_speech TEXT NOT NULL,
      definition TEXT,
      example_sentence TEXT,
      cefr_level TEXT NOT NULL,
      category TEXT,
      chapter_ref INTEGER,
      FOREIGN KEY (chapter_ref) REFERENCES chapters(id)
    );
  `);

  const chaptersData = [
    [
      1,
      "The Parts of Speech",
      "Nouns, Pronouns, Verbs, Adjectives, Adverbs, Prepositions, Conjunctions, Interjections",
      "A1",
    ],
    [
      2,
      "Sentences",
      "Subjects, Predicates, Direct/Indirect Objects, 4 Types of Sentences",
      "A2",
    ],
    [
      3,
      "Phrases",
      "Prepositional, Infinitive, Participial, Gerundial, Appositives",
      "B1",
    ],
    [
      4,
      "Clauses",
      "Independent and Subordinate Clauses (Adjective, Adverb, Noun)",
      "B1",
    ],
    [
      5,
      "Sentence Structures",
      "Simple, Compound, Complex, Compound-Complex Sentences",
      "B1",
    ],
    [
      6,
      "Special Issues with Pronouns",
      "Pronoun Cases (I vs Me, Who vs Whom), Reflexive, Singular Indefinites",
      "B1",
    ],
    [
      7,
      "Special Issues with Verbs",
      "Verb Tenses, Irregular Verbs, Active/Passive Voice, Subjunctive Mood",
      "B2",
    ],
    [
      8,
      "Commas",
      "Series Commas, Compound Sentences, Introductory Elements, Interruptions",
      "A2",
    ],
    [
      9,
      "Punctuation (Except Commas)",
      "Periods, Question Marks, Semicolons, Colons, Dashes, Quotes, Italics",
      "B1",
    ],
    [
      10,
      "Capitalization",
      "Proper Nouns, Titles, Directions, Seasons, School Courses",
      "A1",
    ],
    [
      11,
      "Important Grammar Issues",
      "Subject-Verb Agreement, Comparatives, Possessives, Numbers, Double Negatives",
      "B2",
    ],
    [
      12,
      "Commonly Confused Words",
      "Dictionary of Usage (Affect/Effect, Lay/Lie, Accept/Except, Advice/Advise)",
      "B2",
    ],
  ];

  db.run("DELETE FROM quiz_questions");
  db.run("DELETE FROM grammar_topics");
  db.run("DELETE FROM chapters");

  const stmtChapter = db.prepare(
    "INSERT OR REPLACE INTO chapters (chapter_number, title, description, cefr_level) VALUES (?, ?, ?, ?)",
  );
  chaptersData.forEach((row) => stmtChapter.run(row));
  stmtChapter.finalize();

  const topicsData = [
    [
      1,
      "1.2",
      "Nouns",
      "A noun is a person, place, thing, idea, or emotion. Common nouns are general; proper nouns start with capital letters.",
      "Susie baked a cake in London.",
      "A1",
    ],
    [
      1,
      "1.3",
      "Pronouns",
      "Pronouns take the place of nouns. Personal pronouns include I, you, he, she, it, we, they, me, him, her, us, them.",
      "Mary baked her famous lasagna.",
      "A1",
    ],
    [
      1,
      "1.4",
      "Action & Linking Verbs",
      "Action verbs show physical or mental action. Linking verbs connect the subject to a word describing it (e.g. is, feel, taste).",
      "She felt tired today.",
      "A2",
    ],
    [
      1,
      "1.5",
      "Adjectives",
      "Adjectives describe nouns or pronouns. They tell how many, what kind, or which ones.",
      "The tall girl wore a blue dress.",
      "A1",
    ],
    [
      1,
      "1.6",
      "Adverbs",
      "Adverbs describe verbs, adjectives, or other adverbs. They often end in -ly and tell how, when, where, or to what extent.",
      "She ran quickly to catch the bus.",
      "A2",
    ],
    [
      1,
      "1.7",
      "Prepositions",
      "Prepositions show relationship in time or place (e.g., in, on, under, between, through).",
      "The cat is sitting under the table.",
      "A2",
    ],
    [
      1,
      "1.8",
      "Conjunctions",
      "Coordinating conjunctions (FANBOYS: for, and, nor, but, or, yet, so) connect words, phrases, or sentences.",
      "I wanted to go, but I had no money.",
      "A2",
    ],
    [
      2,
      "2.2",
      "Subjects & Predicates",
      "The subject is who/what the sentence is about. The predicate is the verb and its modifiers.",
      "The big brown dog barking loudly scaring us.",
      "A2",
    ],
    [
      3,
      "3.3",
      "Infinitive Phrases",
      "An infinitive is 'to' + verb. It functions as a noun, adjective, or adverb.",
      "To become a doctor is my greatest dream.",
      "B1",
    ],
    [
      4,
      "4.3",
      "Adjective Clauses",
      "A subordinate clause modifying a noun, starting with relative pronouns (who, whom, whose, which, that).",
      "This is the book that I read last week.",
      "B1",
    ],
    [
      6,
      "6.2",
      "Pronoun Cases (I vs Me)",
      "Use nominative pronouns (I, he, she, we, they) for subjects. Use objective pronouns (me, him, her, us, them) for objects.",
      "He gave the tickets to Judy and me.",
      "B1",
    ],
    [
      7,
      "7.2",
      "Verb Tenses & Past Perfect",
      "Use past perfect (had + past participle) for an action that happened before another past action.",
      "Mary told me that she had seen that movie.",
      "B2",
    ],
    [
      7,
      "7.5",
      "Active vs Passive Voice",
      "In active voice, the subject performs the action. In passive voice, the subject receives the action.",
      "Active: She drove the car. Passive: The car was driven by her.",
      "B2",
    ],
    [
      8,
      "8.3",
      "Commas in Compound Sentences",
      "Use a comma before a FANBOYS conjunction connecting two independent sentences.",
      "I live in Sweden, and my brother lives in Utah.",
      "A2",
    ],
    [
      12,
      "12.1",
      "Affect vs Effect",
      "Affect is usually a verb (to influence). Effect is usually a noun (a result).",
      "The rain affected the event; the effect was disastrous.",
      "B2",
    ],
  ];

  const stmtTopic = db.prepare(
    "INSERT OR REPLACE INTO grammar_topics (chapter_id, topic_code, title, explanation, example_sentence, cefr_level) VALUES (?, ?, ?, ?, ?, ?)",
  );
  topicsData.forEach((row) => stmtTopic.run(row));
  stmtTopic.finalize();

  const quizData = [
    [
      1,
      "Which word in the sentence is a proper noun? 'We went to Stockholm last summer.'",
      "went",
      "Stockholm",
      "summer",
      "last",
      "b",
      "'Stockholm' is a specific place name and capitalized.",
      "A1",
    ],
    [
      2,
      "Choose the correct pronoun: 'Paul and ____ cooked dinner tonight.'",
      "me",
      "I",
      "myself",
      "him",
      "b",
      "'I' is part of the compound subject of the verb 'cooked'.",
      "A1",
    ],
    [
      3,
      "Identify the linking verb: 'The soup tastes delicious.'",
      "soup",
      "tastes",
      "delicious",
      "none",
      "b",
      "'tastes' connects the subject 'soup' to its description 'delicious'.",
      "A2",
    ],
    [
      4,
      "Choose the correct form: 'She gave the tickets to my sister and ____.'",
      "I",
      "me",
      "myself",
      "we",
      "b",
      "'me' is the object of the preposition 'to'.",
      "B1",
    ],
    [
      5,
      "Which of the following sentences is a compound sentence?",
      "The sun set behind the mountains, and the temperature dropped rapidly.",
      "The wind howled loudly through the dark night.",
      "Although she was tired, she finished her homework before bedtime.",
      "Walking down the quiet street, he listened to the rustling leaves.",
      "a",
      "A compound sentence contains two independent clauses joined by a coordinating conjunction such as 'and'.",
      "B1",
    ],
    [
      6,
      "Which sentence is written in passive voice?",
      "He stopped at the corner.",
      "Did you put the groceries away?",
      "The dress was made by my grandmother.",
      "I lost my keys.",
      "c",
      "The subject 'dress' receives the action of being made.",
      "B2",
    ],
    [
      7,
      "Choose the correct word: 'The rain had a strong ____ on our travel plans.'",
      "affect",
      "effect",
      "affected",
      "effected",
      "b",
      "'Effect' is a noun meaning result or impact.",
      "B2",
    ],
    [
      8,
      "Which sentence is punctuated correctly?",
      "I am going to college next year, my sister is too.",
      "I am going to college next year; my sister is too.",
      "I am going to college next year my sister is too.",
      "I am going to college next year: my sister is too.",
      "b",
      "Two independent clauses can be connected with a semicolon.",
      "B1",
    ],
    [
      9,
      "Select the correct sentence:",
      "If I was rich, I would buy a mansion.",
      "If I were rich, I would buy a mansion.",
      "If I am rich, I would buy a mansion.",
      "If I be rich, I would buy a mansion.",
      "b",
      "Subjunctive mood uses 'were' for hypothetical or untrue conditions.",
      "B2",
    ],
    [
      10,
      "Fill in the blank: 'Neither of the boys ____ bringing his homework.'",
      "is",
      "are",
      "were",
      "have been",
      "a",
      "'Neither' is a singular indefinite pronoun and takes a singular verb 'is'.",
      "B1",
    ],
  ];

  const stmtQuiz = db.prepare(
    "INSERT OR REPLACE INTO quiz_questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, cefr_level) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
  );
  quizData.forEach((row) => stmtQuiz.run(row));
  stmtQuiz.finalize();

  const vocabData = [
    // A1
    [
      "Accept",
      "Acceptera / Godta",
      "Verb",
      "To receive willingly or agree to",
      "She accepted the gift with a smile.",
      "A1",
      "General",
      12,
    ],
    [
      "Almost",
      "Nästan",
      "Adverb",
      "Nearly, all but",
      "I am almost ready for school.",
      "A1",
      "General",
      12,
    ],
    [
      "Because",
      "Eftersom / Därför att",
      "Conjunction",
      "For the reason that",
      "I stayed home because I was sick.",
      "A1",
      "Grammar Term",
      1,
    ],
    [
      "Different",
      "Olika / Annorlunda",
      "Adjective",
      "Not the same as another",
      "Swedish and English are different languages.",
      "A1",
      "General",
      11,
    ],
    [
      "Paragraph",
      "Stycke",
      "Noun",
      "A distinct section of writing",
      "Read the first paragraph of the text.",
      "A1",
      "Academic",
      9,
    ],
    [
      "Pronoun",
      "Pronomen",
      "Noun",
      "A word taking the place of a noun",
      "'She' is a personal pronoun.",
      "A1",
      "Grammar Term",
      1,
    ],
    [
      "Singular",
      "Ental / Singular",
      "Adjective",
      "Referring to one person or thing",
      "'Cat' is a singular noun.",
      "A1",
      "Grammar Term",
      1,
    ],
    [
      "Vocabulary",
      "Ordförråd",
      "Noun",
      "The body of words used in a language",
      "Reading books improves your vocabulary.",
      "A1",
      "Academic",
      12,
    ],
    [
      "Sentence",
      "Mening / Sats",
      "Noun",
      "A set of words expressing a complete thought",
      "Write a complete sentence in English.",
      "A1",
      "Grammar Term",
      2,
    ],
    [
      "Subject",
      "Subjekt",
      "Noun",
      "The person or thing performing the verb action",
      "In 'The dog barked', 'dog' is the subject.",
      "A1",
      "Grammar Term",
      2,
    ],
    [
      "Verb",
      "Verb / Handling",
      "Noun",
      "A word used to describe an action or state",
      "'Run' and 'is' are verbs.",
      "A1",
      "Grammar Term",
      1,
    ],
    [
      "Noun",
      "Substantiv",
      "Noun",
      "A word referring to a person, place, or thing",
      "'Stockholm' is a proper noun.",
      "A1",
      "Grammar Term",
      1,
    ],
    [
      "Adjective",
      "Adjektiv",
      "Noun",
      "A word describing a noun",
      "'Blue' and 'happy' are adjectives.",
      "A1",
      "Grammar Term",
      1,
    ],
    [
      "Adverb",
      "Adverb",
      "Noun",
      "A word modifying a verb, adjective, or adverb",
      "He ran quickly.",
      "A1",
      "Grammar Term",
      1,
    ],
    [
      "Question",
      "Fråga",
      "Noun",
      "A sentence worded to elicit information",
      "Answer the teacher's question.",
      "A1",
      "General",
      9,
    ],
    [
      "Plural",
      "Flertal / Plural",
      "Adjective",
      "Referring to more than one",
      "'Dogs' is the plural form of 'dog'.",
      "A1",
      "Grammar Term",
      11,
    ],
    [
      "Capital",
      "Huvudstad / Stor bokstav",
      "Noun",
      "A seat of government or uppercase letter",
      "Stockholm is the capital of Sweden.",
      "A1",
      "Capitalization",
      10,
    ],
    [
      "Example",
      "Exempel",
      "Noun",
      "A sample or instance illustrating a rule",
      "Can you give me an example?",
      "A1",
      "Academic",
      1,
    ],
    [
      "Practice",
      "Övning / Träna",
      "Noun/Verb",
      "Repeated exercise to improve skill",
      "Practice makes perfect.",
      "A1",
      "Academic",
      1,
    ],
    [
      "Answer",
      "Svar / Svara",
      "Noun/Verb",
      "A response to a question",
      "Write your answer on the paper.",
      "A1",
      "General",
      2,
    ],

    // A2
    [
      "Already",
      "Redan",
      "Adverb",
      "Before now or a specified time",
      "They have already finished dinner.",
      "A2",
      "General",
      12,
    ],
    [
      "Article",
      "Artikel",
      "Noun",
      "Words such as 'a', 'an', or 'the'",
      "English has definite and indefinite articles.",
      "A2",
      "Grammar Term",
      1,
    ],
    [
      "Both",
      "Båda / Både",
      "Pronoun/Adjective",
      "One and the other together",
      "Both students scored top marks.",
      "A2",
      "Grammar Term",
      6,
    ],
    [
      "Cause",
      "Orsak / Orsaka",
      "Noun/Verb",
      "A person or thing giving rise to an action",
      "What was the cause of the noise?",
      "A2",
      "Academic",
      2,
    ],
    [
      "Conjunction",
      "Konjunktion / Bindeord",
      "Noun",
      "A word joining words or clauses",
      "'And' and 'but' are conjunctions.",
      "A2",
      "Grammar Term",
      1,
    ],
    [
      "Description",
      "Beskrivning",
      "Noun",
      "A spoken or written representation",
      "Provide a short description of the place.",
      "A2",
      "Academic",
      1,
    ],
    [
      "Desert",
      "Öken",
      "Noun",
      "A dry, barren region of land",
      "The Sahara is a hot desert.",
      "A2",
      "Commonly Confused",
      12,
    ],
    [
      "Dessert",
      "Efterrätt",
      "Noun",
      "Sweet food eaten at the end of a meal",
      "We had chocolate cake for dessert.",
      "A2",
      "Commonly Confused",
      12,
    ],
    [
      "Either",
      "Antingen / Vilken som helst",
      "Conjunction",
      "One or the other of two",
      "You can choose either tea or coffee.",
      "A2",
      "Grammar Term",
      6,
    ],
    [
      "Fewer",
      "Färre",
      "Adjective",
      "A smaller number of countable items",
      "There are fewer mistakes in your essay.",
      "A2",
      "Commonly Confused",
      11,
    ],
    [
      "Healthy",
      "Frisk / Hälsosam",
      "Adjective",
      "In good physical condition",
      "Eating fruit keeps you healthy.",
      "A2",
      "Commonly Confused",
      12,
    ],
    [
      "Identify",
      "Identifiera / Känna igen",
      "Verb",
      "Establish who or what something is",
      "Identify the main verb in the sentence.",
      "A2",
      "Academic",
      1,
    ],
    [
      "Interrupt",
      "Avbryta",
      "Verb",
      "To stop someone while they are speaking",
      "Please do not interrupt the speaker.",
      "A2",
      "General",
      8,
    ],
    [
      "Irregular",
      "Oregelbunden",
      "Adjective",
      "Not following normal grammatical rules",
      "'Swim' is an irregular verb.",
      "A2",
      "Grammar Term",
      7,
    ],
    [
      "Loose",
      "Lös / Sittande löst",
      "Adjective",
      "Not firmly fixed or tight",
      "My shoe lace is loose.",
      "A2",
      "Commonly Confused",
      12,
    ],
    [
      "Lose",
      "Förlora / Tappa",
      "Verb",
      "Be deprived of or fail to keep",
      "Be careful not to lose your key.",
      "A2",
      "Commonly Confused",
      12,
    ],
    [
      "Misplace",
      "Förlägga / Tappa bort",
      "Verb",
      "To place something where it cannot be found",
      "I misplaced my English workbook.",
      "A2",
      "General",
      11,
    ],
    [
      "Necessary",
      "Nödvändig",
      "Adjective",
      "Required or essential",
      "Is it necessary to write in pen?",
      "A2",
      "Spelling",
      11,
    ],
    [
      "Neither",
      "Varken / Ingendera",
      "Conjunction",
      "Not one nor the other of two",
      "Neither answer is correct.",
      "A2",
      "Grammar Term",
      6,
    ],
    [
      "Opposite",
      "Motsats / Motsatt",
      "Adjective/Noun",
      "Completely different in nature",
      "'Cold' is the opposite of 'hot'.",
      "A2",
      "General",
      12,
    ],
    [
      "Possessive",
      "Ägande / Genitiv",
      "Adjective",
      "Showing ownership or possession",
      "'My' and 'your' are possessive words.",
      "A2",
      "Grammar Term",
      11,
    ],
    [
      "Preposition",
      "Preposition",
      "Noun",
      "Word placed before a noun to show direction or place",
      "'Under' and 'in' are prepositions.",
      "A2",
      "Grammar Term",
      1,
    ],
    [
      "Punctuation",
      "Interpunktion / Teckenstättning",
      "Noun",
      "Marks used in writing to clarify meaning",
      "Check your text for correct punctuation.",
      "A2",
      "Punctuation",
      9,
    ],
    [
      "Statement",
      "Påstående / Uttalande",
      "Noun",
      "A definite or clear expression in speech/writing",
      "A declarative sentence makes a statement.",
      "A2",
      "Grammar Term",
      2,
    ],
    [
      "Compare",
      "Jämföra",
      "Verb",
      "Estimate or measure similarity/dissimilarity",
      "Compare your answers with a partner.",
      "A2",
      "Academic",
      11,
    ],

    // B1
    [
      "Advice",
      "Råd",
      "Noun",
      "An opinion or recommendation given",
      "My teacher gave me good advice.",
      "B1",
      "Commonly Confused",
      12,
    ],
    [
      "Advise",
      "Råda / Ge råd",
      "Verb",
      "To give counsel or a recommendation",
      "I advise you to review the grammar rules.",
      "B1",
      "Commonly Confused",
      12,
    ],
    [
      "Although",
      "Fastän / Även om",
      "Conjunction",
      "In spite of the fact that",
      "Although it rained, we played football.",
      "B1",
      "Grammar Term",
      4,
    ],
    [
      "Clause",
      "Sats",
      "Noun",
      "A group of words containing subject and verb",
      "A complex sentence has a dependent clause.",
      "B1",
      "Grammar Term",
      4,
    ],
    [
      "Collective",
      "Kollektiv / Gemensam",
      "Adjective",
      "Denoting a group of individuals",
      "'Team' is a collective noun.",
      "B1",
      "Grammar Term",
      1,
    ],
    [
      "Comparison",
      "Jämförelse",
      "Noun",
      "The act or instance of comparing",
      "Make a comparison between the two texts.",
      "B1",
      "Grammar Term",
      11,
    ],
    [
      "Complex",
      "Sammansatt / Komplex",
      "Adjective",
      "Consisting of many different connected parts",
      "This is a complex sentence structure.",
      "B1",
      "Grammar Term",
      5,
    ],
    [
      "Compound",
      "Sammansatt",
      "Adjective",
      "Formed from two or more parts",
      "A compound sentence uses 'and' or 'but'.",
      "B1",
      "Grammar Term",
      5,
    ],
    [
      "Definite",
      "Bestämd / Tydlig",
      "Adjective",
      "Clearly stated or decided",
      "We need a definite answer today.",
      "B1",
      "Academic",
      11,
    ],
    [
      "Effect",
      "Effekt / Verkan",
      "Noun",
      "A change that is a result or consequence",
      "The medicine had a positive effect.",
      "B1",
      "Commonly Confused",
      12,
    ],
    [
      "Environment",
      "Miljö",
      "Noun",
      "The surroundings in which a person lives",
      "We should care for the environment.",
      "B1",
      "Academic",
      11,
    ],
    [
      "Essential",
      "Väsentlig / Nödvändig",
      "Adjective",
      "Absolutely necessary or extremely important",
      "Good grammar is essential for clear writing.",
      "B1",
      "Grammar Term",
      6,
    ],
    [
      "Exclamation",
      "Utrop",
      "Noun",
      "A sudden cry or remark expressing emotion",
      "'Help!' is an exclamation.",
      "B1",
      "Punctuation",
      9,
    ],
    [
      "Fragment",
      "Fragment / Ofullständig sats",
      "Noun",
      "A small part broken off; incomplete sentence",
      "Avoid using a sentence fragment in essays.",
      "B1",
      "Grammar Term",
      5,
    ],
    [
      "Healthful",
      "Hälsobringande",
      "Adjective",
      "Conducive to good health",
      "Vegetables are healthful foods.",
      "B1",
      "Commonly Confused",
      12,
    ],
    [
      "However",
      "Dock / Emellertid",
      "Adverb",
      "Used to introduce a contrasting statement",
      "I love dogs; however, I am allergic.",
      "B1",
      "Punctuation",
      8,
    ],
    [
      "Immediate",
      "Omedelbar / Direkt",
      "Adjective",
      "Occurring or done at once",
      "We need an immediate decision.",
      "B1",
      "Academic",
      8,
    ],
    [
      "Imperative",
      "Uppmanande / Imperativ",
      "Adjective/Noun",
      "Giving an authoritative command",
      "'Clean your room!' is an imperative sentence.",
      "B1",
      "Grammar Term",
      2,
    ],
    [
      "Independent",
      "Självständig / Oberoende",
      "Adjective",
      "Free from outside control; self-governing",
      "An independent clause stands alone.",
      "B1",
      "Grammar Term",
      4,
    ],
    [
      "Interjection",
      "Interjektion / Utropsord",
      "Noun",
      "An exclamation inserted into speech",
      "'Ouch!' is an interjection.",
      "B1",
      "Grammar Term",
      1,
    ],
    [
      "Objective",
      "Objektiv / Mål",
      "Noun/Adjective",
      "Not influenced by personal feelings",
      "'Me' is an objective pronoun.",
      "B1",
      "Grammar Term",
      6,
    ],
    [
      "Occur",
      "Inträffa / Ske",
      "Verb",
      "To happen or take place",
      "Mistakes can occur when you rush.",
      "B1",
      "Academic",
      11,
    ],
    [
      "Passive",
      "Passiv",
      "Adjective",
      "Accepting what happens without active response",
      "The sentence was written in passive voice.",
      "B1",
      "Grammar Term",
      7,
    ],
    [
      "Predicate",
      "Predikat",
      "Noun",
      "The part of a sentence containing the verb",
      "The predicate tells what the subject does.",
      "B1",
      "Grammar Term",
      2,
    ],
    [
      "Principal",
      "Rektor / Huvudsaklig",
      "Noun/Adjective",
      "Head of a school or main item",
      "Mr. Adams is our school principal.",
      "B1",
      "Commonly Confused",
      12,
    ],
    [
      "Principle",
      "Princip / Grundregel",
      "Noun",
      "A fundamental truth or rule of conduct",
      "Honesty is an important moral principle.",
      "B1",
      "Commonly Confused",
      12,
    ],
    [
      "Regardless",
      "Oavsett",
      "Adverb",
      "Without paying attention to present conditions",
      "We will go hiking regardless of the weather.",
      "B1",
      "Commonly Confused",
      12,
    ],
    [
      "Semicolon",
      "Semikolon",
      "Noun",
      "Punctuation mark (;) connecting independent clauses",
      "Use a semicolon to connect related sentences.",
      "B1",
      "Punctuation",
      9,
    ],
    [
      "Superlative",
      "Superlativ",
      "Adjective/Noun",
      "Expressing the highest degree of comparison",
      "'Tallest' is the superlative form.",
      "B1",
      "Grammar Term",
      11,
    ],
    [
      "Variety",
      "Variation / Mångfald",
      "Noun",
      "The quality or state of being different",
      "Use a variety of sentence lengths.",
      "B1",
      "Academic",
      5,
    ],
    [
      "Lay",
      "Lägga",
      "Verb",
      "To put down gently (requires object)",
      "Lay your pencil down on the desk.",
      "B1",
      "Commonly Confused",
      12,
    ],
    [
      "Lie",
      "Ligga / Ljuga",
      "Verb",
      "To be in a horizontal position (no object)",
      "I need to lie down for a rest.",
      "B1",
      "Commonly Confused",
      12,
    ],
    [
      "Lend",
      "Låna ut",
      "Verb",
      "To grant use of something temporarily",
      "Can you lend me a pencil?",
      "B1",
      "Commonly Confused",
      12,
    ],

    // B2
    [
      "Affect",
      "Påverka",
      "Verb",
      "To produce an effect upon or influence",
      "Cold weather can affect your health.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Allusion",
      "Anspelning / Syftning",
      "Noun",
      "An indirect reference to something",
      "The author made an allusion to Shakespeare.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Antecedent",
      "Förled / Syftningsord",
      "Noun",
      "A word to which a pronoun refers back",
      "In 'John lost his bag', 'John' is the antecedent.",
      "B2",
      "Grammar Term",
      1,
    ],
    [
      "Appositive",
      "Apposition / Tilläggsförklaring",
      "Noun",
      "A noun placed next to another to describe it",
      "My friend, an artist, painted this picture.",
      "B2",
      "Grammar Term",
      3,
    ],
    [
      "Conscience",
      "Samvete",
      "Noun",
      "Inner sense of what is right or wrong",
      "Her conscience bothered her after telling a lie.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Conscious",
      "Medveten",
      "Adjective",
      "Aware of one's surroundings or existence",
      "He was conscious of his grammar mistakes.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Complement",
      "Komplettera / Komplement",
      "Verb/Noun",
      "Something that completes or brings to perfection",
      "The red scarf complements her coat.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Compliment",
      "Beröm / Berömma",
      "Noun/Verb",
      "An expression of praise or admiration",
      "He gave her a lovely compliment.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Continual",
      "Ständig / Återkommande",
      "Adjective",
      "Frequently recurring; happening repeatedly",
      "There were continual interruptions during class.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Continuous",
      "Oavbruten",
      "Adjective",
      "Without interruption; unbroken",
      "We heard the continuous flow of water.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Discreet",
      "Diskret / Hänsynsfull",
      "Adjective",
      "Careful and circumspect in speech or action",
      "Please be discreet with confidential info.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Discrete",
      "Särskild / Fristående",
      "Adjective",
      "Individually separate and distinct",
      "The course is divided into three discrete units.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Disinterested",
      "Opartisk",
      "Adjective",
      "Not influenced by personal advantage; impartial",
      "A judge must remain a disinterested party.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Eminent",
      "Framstående",
      "Adjective",
      "Famous and respected within a profession",
      "An eminent professor delivered the lecture.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Emigrate",
      "Utvandra / Emigrera",
      "Verb",
      "To leave one's own country permanently",
      "Many Swedes emigrated to America in the 1800s.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Immigrate",
      "Invandra / Immigrera",
      "Verb",
      "To come to live permanently in a foreign country",
      "His family immigrated to Sweden recently.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Formerly",
      "Tidigare / Förr",
      "Adverb",
      "In the past; at an earlier period",
      "This building was formerly a school.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Formally",
      "Formellt",
      "Adverb",
      "In accordance with official rules or convention",
      "He was formally introduced to the king.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Gerund",
      "Gerundium / Verbalsubstantiv",
      "Noun",
      "A verb form ending in -ing acting as a noun",
      "'Reading' in 'Reading is fun' is a gerund.",
      "B2",
      "Grammar Term",
      3,
    ],
    [
      "Illusion",
      "Illusion / Inbillning",
      "Noun",
      "A false idea, belief, or deceptive appearance",
      "The desert heat created a mirage illusion.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Imply",
      "Antyda",
      "Verb",
      "Strongly suggest the truth without direct state",
      "Are you implying that I am mistaken?",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Infer",
      "Dra en slutsats",
      "Verb",
      "Deduce information from reasoning or evidence",
      "From the clouds, we inferred it would rain.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Latter",
      "Sistnämnda",
      "Adjective",
      "Denoting the second of two things mentioned",
      "Of cats and dogs, I prefer the latter.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Former",
      "Förstnämnda",
      "Adjective",
      "Denoting the first of two things mentioned",
      "Of cats and dogs, I prefer the former.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Nominative",
      "Nominativ / Subjektiv form",
      "Noun/Adjective",
      "Case used for the subject of a verb",
      "'She' is in the nominative case.",
      "B2",
      "Grammar Term",
      6,
    ],
    [
      "Participle",
      "Particip",
      "Noun",
      "A verb form functioning as an adjective",
      "'Broken' in 'broken window' is a participle.",
      "B2",
      "Grammar Term",
      3,
    ],
    [
      "Precede",
      "Föregå",
      "Verb",
      "To come before something in time or order",
      "Chapter 1 precedes Chapter 2.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Proceed",
      "Fortsätta / Gå vidare",
      "Verb",
      "To begin or continue a course of action",
      "You may proceed with your presentation.",
      "B2",
      "Commonly Confused",
      12,
    ],
    [
      "Redundant",
      "Överflödig",
      "Adjective",
      "Not or no longer needed or useful",
      "'Free gift' is a redundant expression.",
      "B2",
      "Style Term",
      11,
    ],
    [
      "Reflexive",
      "Reflexiv",
      "Adjective",
      "Referring back to the subject of the clause",
      "'Myself' is a reflexive pronoun.",
      "B2",
      "Grammar Term",
      6,
    ],
    [
      "Subordinate",
      "Underordnad",
      "Adjective/Noun",
      "Lower in rank; secondary clause",
      "A subordinate clause needs a main clause.",
      "B2",
      "Grammar Term",
      4,
    ],
    [
      "Transitive",
      "Transitiv",
      "Adjective",
      "(Of a verb) requiring a direct object",
      "'Bought' is a transitive verb in 'I bought a car'.",
      "B2",
      "Grammar Term",
      1,
    ],
  ];

  const vocabularyDefinitions = {
    "B1:accommodation": "A place where someone lives or stays.",
    "B1:achievement": "Something successfully completed or achieved.",
    "B1:advantage":
      "A condition or circumstance that puts one in a favorable position.",
    "B1:advertise":
      "To tell people publicly about a product, service, or event.",
    "B1:afford": "To have enough money to pay for something.",
    "B1:ambition": "A strong desire to achieve something.",
    "B1:appointment":
      "An arrangement to meet someone at a particular time and place.",
    "B1:arrangement": "An agreement or plan made for a particular purpose.",
    "B1:attitude":
      "A settled way of thinking or feeling about someone or something.",
    "B1:available": "Able to be used, obtained, or reached.",
    "B1:average": "The usual or typical amount; calculated as a mean.",
    "B1:benefit": "An advantage or profit gained from something.",
    "B1:brilliant": "Extremely clever, impressive, or excellent.",
    "B1:campaign":
      "A series of organized actions or events intended to achieve a goal.",
    "B1:cancel": "To decide that an arranged event will not happen.",
    "B1:casual": "Relaxed and suitable for ordinary or informal situations.",
    "B1:celebrity": "A famous person, especially in entertainment or sport.",
    "B1:challenge":
      "A task or situation that tests someone's ability or skill.",
    "B1:charge": "To ask someone to pay; the amount asked for something.",
    "B1:cheerful": "Happy and positive.",
    "B1:chemical":
      "Relating to chemistry; a substance made by or used in a chemical process.",
    "B1:circumstance":
      "A fact or condition connected with an event or situation.",
    "B1:climate": "The usual weather conditions of a place.",
    "B1:colleague": "A person you work with.",
    "B1:comfortable": "Providing a pleasant, relaxed physical feeling.",
    "B1:commitment":
      "The state or quality of being dedicated to a cause or activity.",
    "B1:compare":
      "To examine two or more things to see how they are similar or different.",
    "B1:compete":
      "To try to be more successful than someone or something else.",
    "B1:completely": "In every way or as much as possible; entirely.",
    "B1:confident": "Feeling certain of your abilities or success.",
    "A2:achieve": "To successfully reach a goal after working hard.",
    "A2:adventure": "An exciting, unusual, or sometimes dangerous experience.",
    "A2:appliance":
      "A device or machine used in a home, usually for housework.",
    "A2:available": "Able to be used, bought, or reached easily.",
    "A2:boring": "Not interesting or dull.",
    "A2:challenge":
      "Something new and difficult that tests your ability or skill.",
    "A2:comfortable":
      "Providing a pleasant, relaxing physical feeling or ease.",
    "A2:compare":
      "To look at two or more things to see how they are similar or different.",
    "A2:confident": "Being certain of your own abilities or success.",
    "A2:dangerous": "Likely to cause harm or injury.",
    "A2:decide": "To make a choice after thinking about possibilities.",
    "A2:delicious": "Having a very pleasant taste or smell.",
    "A2:discover": "To find something out or find a place for the first time.",
    "A2:environment":
      "The natural world or the surroundings in which people, animals, and plants live.",
    "A2:equipment":
      "The necessary items or tools needed for a particular purpose.",
    "A2:exciting": "Causing great enthusiasm and eagerness.",
    "A2:experience":
      "Knowledge or skill gained by doing or seeing things over time.",
    "A2:fascinating": "Extremely interesting and captivating.",
    "A2:improve": "To make or become better.",
    "A2:independent":
      "Able to think and do things on your own without needing help.",
    "A2:invention":
      "A new product, machine, or idea created for the first time.",
    "A2:language":
      "A system of communication used by a particular country or community.",
    "A2:memory":
      "Something you remember from the past, or how much data a computer can store.",
    "A2:message":
      "A written, digital, or spoken piece of information sent to someone.",
    "A2:opinion": "A personal view, judgment, or attitude about something.",
    "A2:possible": "Able to happen, be done, or be achieved.",
    "A2:practice": "Repeating an activity regularly to improve your skill.",
    "A2:protect": "To keep someone or something safe from harm.",
    "A2:receive": "To get or be given something.",
    "A2:successful": "Achieving the results you wanted or hoped for.",
  };

  const requestedVocabulary = [
    ["accommodation", "boende", "Noun", "B1"],
    ["achievement", "prestation / framsteg", "Noun", "B1"],
    ["advantage", "fördel", "Noun", "B1"],
    ["advertise", "annonsera", "Verb", "B1"],
    ["afford", "ha råd med", "Verb", "B1"],
    ["ambition", "ambition", "Noun", "B1"],
    ["appointment", "tidsbeställning / möte", "Noun", "B1"],
    ["arrangement", "överenskommelse / arrangemang", "Noun", "B1"],
    ["attitude", "attityd / inställning", "Noun", "B1"],
    ["available", "tillgänglig", "Adjective", "B1"],
    ["average", "genomsnittlig / genomsnitt", "Adjective/Noun", "B1"],
    ["benefit", "fördel / nytta", "Noun/Verb", "B1"],
    ["brilliant", "briljant / utmärkt", "Adjective", "B1"],
    ["campaign", "kampanj", "Noun", "B1"],
    ["cancel", "ställa in / avboka", "Verb", "B1"],
    ["casual", "ledig / vardaglig", "Adjective", "B1"],
    ["celebrity", "kändis", "Noun", "B1"],
    ["challenge", "utmaning", "Noun/Verb", "B1"],
    ["charge", "ta betalt / avgift", "Noun/Verb", "B1"],
    ["cheerful", "glad / munter", "Adjective", "B1"],
    ["chemical", "kemisk", "Adjective/Noun", "B1"],
    ["circumstance", "omständighet", "Noun", "B1"],
    ["climate", "klimat", "Noun", "B1"],
    ["colleague", "kollega", "Noun", "B1"],
    ["comfortable", "bekväm", "Adjective", "B1"],
    ["commitment", "åtagande / engagemang", "Noun", "B1"],
    ["compare", "jämföra", "Verb", "B1"],
    ["compete", "tävla", "Verb", "B1"],
    ["completely", "fullständigt", "Adverb", "B1"],
    ["confident", "självsäker / säker", "Adjective", "B1"],
    ["achieve", "uppnå / klara av", "Verb", "A2"],
    ["adventure", "äventyr", "Noun", "A2"],
    ["appliance", "apparat / hushållsmaskin", "Noun", "A2"],
    ["available", "tillgänglig", "Adjective", "A2"],
    ["boring", "tråkig", "Adjective", "A2"],
    ["challenge", "utmaning", "Noun/Verb", "A2"],
    ["comfortable", "bekväm", "Adjective", "A2"],
    ["compare", "jämföra", "Verb", "A2"],
    ["confident", "självsäker", "Adjective", "A2"],
    ["dangerous", "farlig", "Adjective", "A2"],
    ["decide", "bestämma sig", "Verb", "A2"],
    ["delicious", "läcker / jättegod", "Adjective", "A2"],
    ["discover", "upptäcka", "Verb", "A2"],
    ["environment", "miljö", "Noun", "A2"],
    ["equipment", "utrustning", "Noun", "A2"],
    ["exciting", "spännande", "Adjective", "A2"],
    ["experience", "erfarenhet / upplevelse", "Noun/Verb", "A2"],
    ["fascinating", "fascinerande", "Adjective", "A2"],
    ["improve", "förbättra", "Verb", "A2"],
    ["independent", "självständig", "Adjective", "A2"],
    ["invention", "uppfinning", "Noun", "A2"],
    ["language", "språk", "Noun", "A2"],
    ["memory", "minne", "Noun", "A2"],
    ["message", "meddelande", "Noun", "A2"],
    ["opinion", "åsikt", "Noun", "A2"],
    ["possible", "möjlig", "Adjective", "A2"],
    ["practice", "träning / övning", "Noun/Verb", "A2"],
    ["protect", "skydda", "Verb", "A2"],
    ["receive", "ta emot", "Verb", "A2"],
    ["successful", "framgångsrik", "Adjective", "A2"],
  ].map(([word, translation, partOfSpeech, level]) => [
    `${word.charAt(0).toUpperCase()}${word.slice(1)}`,
    `${translation.charAt(0).toUpperCase()}${translation.slice(1)}`,
    partOfSpeech,
    vocabularyDefinitions[`${level}:${word}`],
    null,
    level,
    "General vocabulary",
    null,
  ]);

  db.run("DELETE FROM vocabulary");
  const stmtVocab = db.prepare(`
    INSERT OR REPLACE INTO vocabulary (
      english_word, swedish_translation, part_of_speech,
      definition, example_sentence, cefr_level, category, chapter_ref
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
  `);
  requestedVocabulary.forEach((row) => stmtVocab.run(row));
  stmtVocab.finalize();

  console.log("✅ Success! Database populated with:");
  console.log("   - 12 Chapters");
  console.log("   - 15 Grammar Topics");
  console.log("   - 10 Quiz Questions");
  console.log("   - 60 Vocabulary Flashcards (A2 - B1)");
  console.log("Saved directly to english_lab.db!");
});

db.close();
